title: Outdoor Buddies
description: Find a Buddy for Hiking, Running, Walking; The Great Outdoors!
google_analytics:
show_downloads: false
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/orgs/outdoor-buddies-new/repositories
website: https://outdoor-buddies-d08trvj81-outdoor-buddies-new.vercel.app/
gems:
  - jekyll-mentions
